# Generated by Django 4.2.16 on 2024-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='Comment',
            new_name='comment',
        ),
    ]
