# Generated by Django 4.2.16 on 2024-10-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_comment_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['timestamp']},
        ),
    ]
